module.exports = {
  branches: [
    "master",
    { name: "next", prerelease: true },
    { name: "hotfix/*", channel: "patch" },
    { name: "rc/*", channel: "rc", prerelease: "rc" },
  ],
  plugins: [
    ["@semantic-release/commit-analyzer", { preset: "conventionalcommits" }],
    ["@semantic-release/release-notes-generator", { preset: "conventionalcommits" }],
    ["@semantic-release/changelog", {
      changelogFile: "CHANGELOG.md",
      changelogTitle: "# Changelog",
      changelogHeader: "All notable changes to this project will be documented in this file.",
      changelogFooter: "This CHANGELOG.md file was generated by semantic-release."
    }],
    ["@google/semantic-release-replace-plugin", {
      replacements: [
        {
          files: ["README.md"],
          from: /Version \d+\.\d+\.\d+(?:-[\w\.]+)?/g,
          to: "Version ${nextRelease.version}"
        }
      ]
    }],
    ["@semantic-release/git", {
      assets: ["CHANGELOG.md", "README.md"],
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
};
