name: Release
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  deployments: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ./.github/actions/release/action.yaml
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}

  sync:
    name: Sync master and next
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Sync master and next
        uses: ./.github/actions/sync/action.yaml
        with:
          main_branch: master
          next_branch: next
          deploy_key: ${{ secrets.DEPLOY_KEY }}
