name: Release (Action Based)
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  deployments: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Release
        uses: ./.github/actions/release
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}

  sync:
    name: Sync master and next
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: next
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Sync master and next
        uses: ./.github/actions/sync
        with:
          main_branch: master
          next_branch: next
          deploy_key: ${{ secrets.DEPLOY_KEY }}

